spring.application.name=chatapp backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/chatapp}
spring.data.mongodb.database=${MONGODB_DATABASE:chatapp}
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/chatapp}
frontend.url=${FRONTEND_URL:http://localhost:5173}
